sudo: false

language: cpp
os: linux
dist: bionic

install:
  - sudo apt-get update
  - ldd --version
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - rm -f miniconda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels slsdetectorgroup
  - conda update -q conda
  - conda info -a

  - conda create -q -n testenv conda-build anaconda-client conda-verify
  - conda activate testenv
  # - conda-build .

script:
  - conda-build .


deploy:
  provider: script
  script: find $HOME/miniconda/conda-bld/${TRAVIS_OS_NAME}-64 -name "*.tar.bz2" -exec anaconda -t $CONDA_TOKEN upload {} \;
  on:
    branch: master
    tags: true

