DESTDIR = bin
PROG= $(DESTDIR)/XRayBoxGui


all: $(PROG) Makefile.gui

clean: 
	if test -e Makefile.gui; then make -f Makefile.gui clean; make -f Makefile.gui mocclean; rm Makefile.gui; else 	make Makefile.gui;make -f Makefile.gui clean; make -f Makefile.gui mocclean;  fi


Makefile.gui: mm

mm:
	qmake -set QT_INSTALL_PREFIX $(QTDIR) && qmake -o Makefile.gui DESTDIR=$(DESTDIR) 


$(PROG): Makefile.gui $(DIR)
	make -f Makefile.gui DESTDIR=$(DESTDIR) 
