package:
  name: xrayboxsoftware
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  - path: ..

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake
    - qt 4.8.*
    - xorg-libxau

  host:
    - libstdcxx-ng
    - libgcc-ng
    - xorg-libxau

  run:
    - libstdcxx-ng
    - libgcc-ng 


outputs:
  - name: slsdetboxlib
    script: copy_client.sh

  - name: slsdetboxgui
    script: copy_gui.sh

    requirements:
      run:
        - qt 4.8.*

  - name: slsdetbox
    script: build_pylib.sh
    requirements:
      build:
        - setuptools
        - python

      host:
        - python
        
      run: 
        - python
        - {{ pin_subpackage('slsdetlib', exact=True) }}


#     test:
#       imports:
#         - sls_detector


