package:
  name: xrayboxsoftware
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  - path: ..

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake
    - qt 4.8.*
    - xorg-libxau

  host:
    - libstdcxx-ng
    - libgcc-ng
    - xorg-libxau

  run:
    - libstdcxx-ng
    - libgcc-ng 


outputs:
  - name: slsdetbox
    script: copy_client.sh
    requirements:
      build:
        - python
      run:
        - python


  - name: slsdetboxgui
    script: copy_gui.sh

    requirements:
      run:
        - qt 4.8.*

#     test:
#       imports:
#         - sls_detector


