package:
  name: xrayboxsoftware
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  - path: ..

build:
  number: 0
  rpaths:
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
    - {{compiler('cxx')}}
    - cmake
    - qt 5
    - xorg-libxau

  host:
    - libstdcxx-ng
    - libgcc-ng
    - xorg-libxau

  run:
    - libstdcxx-ng
    - libgcc-ng 


outputs:
  - name: slsdetboxlib
    script: copy_client.sh


  - name: slsdetboxgui
    script: copy_gui.sh

    requirements:
      run:
        - qt 5

  - name: slsdetbox
    noarch: python
    script: build_pylib.sh


    requirements:
      build:
        - python
        - setuptools
        

      host:
        - python

      run: 
        - python
        - {{ pin_subpackage('slsdetboxlib', exact=True) }}


#     test:
#       imports:
#         - sls_detector


